/* autogenerated by Processing revision 1307 on 2025-09-19 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class tallero0 extends PApplet {

float angle = 0;
float scale = .10f;
boolean scaleTop = false;
float pos = width/2;
boolean posTop = false;

public void setup() {
  /* size commented out by preprocessor */; // P3D enables 3D rendering
}

public void draw() {
  background(30);
  lights(); // Adds default lighting

  translate(pos, height/2, 0); // Move to center
  rotateX(angle);
  rotateY(angle); // Different speed for variation
  
  scale(scale);
  
  fill(0, 150, 255);
  stroke(255);
  box(200); // 3D cube with size 200
  
  if(scaleTop)
    scale += 0.01f;
  else
    scale -= 0.01f;
   
  if(posTop)
    pos += 3;
  else
    pos -= 3;
  
  if(pos > width)
    posTop = false;
  else if (pos < 5.2f)
    posTop = true;
  
  if(scale > 2)
    scaleTop = false;
  else if (scale < 0.2f)
    scaleTop = true;
    
    
  angle += 0.02f; // Rotation speed
}


  public void settings() { size(600, 600, P3D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "tallero0" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
